spring:
  devtools:
    restart:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:postgresql://localhost:5432/mlibrary
#    url: jdbc:postgresql://localhost:5432/mlibrary
    username: mlibrary
    password: lib123
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false


microblink:
  api:
    url: https://api.microblink.com
    blink-id-path: /recognize/execute
    web-api-key: d87fa6658b574e09bb28184fe2e2c609
    web-api-secret: f3ed571c-70d2-4aa8-904d-b4447f2b031d
